#let rows = (
[clawhub], [Agent tooling], [TypeScript], [9,494], [2026-10-07], [MIT], [L], [*study* S], [Skill/plugin registry; not inspected],
[Peekaboo], [Agent tooling], [Swift], [5,260], [2026-10-07], [MIT], [M], [*study* S], [macOS screenshot/UI-automation CLI+MCP; overlaps shot, mirroir, computer-lease],
[mcporter], [Agent tooling], [TypeScript], [5,053], [2026-10-07], [MIT], [H], [*skill* S], [Call/compose MCP servers from TS or generate CLIs; TS, MIT, Node 24],
[acpx], [Agent tooling], [TypeScript], [3,321], [2026-10-07], [MIT], [M], [*study* S], [Headless ACP client; relevant to delegating-work fan-out],
[clawsweeper], [Agent tooling], [TypeScript], [1,994], [2026-10-08], [MIT], [L], [*ignore* -], [Issue/PR triage bot for openclaw],
[crabbox], [Agent tooling], [Go], [1,452], [2026-10-08], [MIT], [L], [*study* S], [Warm box + sync diff + run suite; remote test runner idea],
[lobster], [Agent tooling], [TypeScript], [1,269], [2026-10-07], [MIT], [M], [*study* S], [Typed JSON workflow shell with approval gates],
[agent-skills], [Agent tooling], [Python], [1,103], [2026-10-07], [MIT], [M], [*skill* S], [Shared SKILL.md workflows (autoreview etc.); cherry-pick via link-repo-skills],
[clawpatch], [Agent tooling], [TypeScript], [813], [2026-10-07], [MIT], [L], [*ignore* -], [Review/patch bots; overlaps own skills],
[AXorcist], [Agent tooling], [Swift], [324], [2026-10-07], [MIT], [L], [*ignore* -], [Swift Accessibility wrapper],
[Tachikoma], [Agent tooling], [Swift], [298], [2026-10-07], [MIT], [L], [*ignore* -], [Swift multi-provider AI SDK],
[crabfleet], [Agent tooling], [Swift], [239], [2026-10-07], [MIT], [L], [*ignore* -], [Mission control for runs (Swift)],
[clawscan], [Agent tooling], [Go], [142], [2026-10-07], [MIT], [M], [*study* S], [Security scanning harness for agent skills; compare to skill-security-auditor],
[clownfish], [Agent tooling], [JavaScript], [62], [2026-10-08], [MIT], [L], [*ignore* -], [Maintainer codex harness],
[turnwire], [Agent tooling], [Go], [12], [2026-10-07], [MIT], [M], [*study* S], [Signed, audited MCP text relay; maps to EQStack thread-isolation rules],
[crabhelm], [Agent tooling], [TypeScript], [3], [2026-10-07], [MIT], [L], [*ignore* -], [Meta orchestrator],
[gogcli], [Apple/Google], [Go], [8,483], [2026-10-07], [MIT], [M], [*skill* S], [Workspace CLI (Gmail, Calendar, Drive...); Calendar/Drive via skill, Gmail stays in gmail-mcp],
[remindctl], [Apple/Google], [Swift], [388], [2026-10-07], [MIT], [L], [*skill* S], [Apple Reminders CLI; thin skill if wanted],
[spogo], [Apple/Google], [Go], [263], [2026-09-25], [MIT], [L], [*ignore* -], [Spotify CLI],
[goplaces], [Apple/Google], [Shell], [261], [2026-10-07], [MIT], [L], [*ignore* -], [Google Places CLI],
[songsee], [Apple/Google], [Go], [81], [2026-10-07], [MIT], [L], [*ignore* -], [Spectrogram CLI],
[openclaw], [Core], [TypeScript], [391,611], [2026-10-08], [MIT], [L], [*study* S], [The agent platform itself (391k stars); channel plugin API worth reading, out of R3 scope],
[community], [Docs/Community], [-], [102], [2026-09-14], [MIT], [L], [*ignore* -], [Discord policy],
[docs], [Docs/Community], [JavaScript], [76], [2026-10-08], [MIT], [L], [*ignore* -], [OpenClaw docs],
[ask-molty], [Docs/Community], [TypeScript], [25], [2026-09-25], [MIT], [L], [*ignore* -], [Docs builder],
[voice-community], [Docs/Community], [-], [12], [2026-08-20], [MIT], [L], [*ignore* -], [Empty],
[rfcs], [Docs/Community], [-], [9], [2026-09-25], [MIT], [L], [*ignore* -], [RFCs],
[.github], [Docs/Community], [-], [8], [2026-08-20], [MIT], [L], [*ignore* -], [Org files],
[carapace], [Docs/Community], [JavaScript], [6], [2026-10-07], [MIT], [L], [*ignore* -], [Design tokens],
[nix-openclaw], [Infra], [Nix], [712], [2026-09-25], [NOASSERTION], [L], [*ignore* -], [Nix packaging],
[openclaw-ansible], [Infra], [Shell], [600], [2026-10-07], [MIT], [L], [*ignore* -], [Hardened install],
[openclaw-enterprise], [Infra], [JavaScript], [365], [2026-10-08], [MIT], [L], [*ignore* -], [Control plane],
[clawdinators], [Infra], [Nix], [158], [2026-10-07], [MIT], [L], [*ignore* -], [NixOS hosts],
[octopool], [Infra], [TypeScript], [136], [2026-10-07], [MIT], [L], [*ignore* -], [GitHub read relay],
[nix-openclaw-tools], [Infra], [Go], [54], [2026-10-07], [MIT], [L], [*ignore* -], [Nix tool packaging],
[homebrew-tap], [Infra], [Python], [40], [2026-10-07], [MIT], [L], [*ignore* -], [Brew tap; where wacli/telecrawl install from],
[clawrouter], [Infra], [JavaScript], [39], [2026-10-07], [MIT], [L], [*ignore* -], [Provider router],
[openclaw-rtt], [Infra], [JavaScript], [33], [2026-10-08], [MIT], [L], [*ignore* -], [Release timing],
[clawsweeper-state-archive-20260731], [Infra], [JavaScript], [17], [2026-09-25], [MIT], [L], [*ignore* -], [Archive],
[clawsweeper.bot], [Infra], [CSS], [15], [2026-07-27], [MIT], [L], [*ignore* -], [Website],
[releases], [Infra], [Python], [13], [2026-10-07], [MIT], [L], [*ignore* -], [Release ledger],
[catalog], [Infra], [JavaScript], [11], [2026-10-08], [MIT], [L], [*ignore* -], [Model catalog],
[Kova], [Infra], [JavaScript], [11], [2026-10-07], [MIT], [L], [*ignore* -], [Runtime validation lab],
[release-workflows], [Infra], [JavaScript], [7], [2026-10-07], [MIT], [M], [*study* S], [Reusable release workflows; compare with msr setup],
[clawsweeper-state], [Infra], [JavaScript], [4], [2026-10-08], [MIT], [L], [*ignore* -], [State store],
[telemetry], [Infra], [JavaScript], [4], [2026-10-03], [MIT], [L], [*ignore* -], [Update-check worker],
[clawgrit-reports], [Infra], [-], [3], [2026-10-07], [none], [L], [*ignore* -], [Perf reports],
[endor-clawsweeper-e2e], [Infra], [JavaScript], [0], [2026-10-01], [none], [L], [*ignore* -], [Fixture],
[clawpdf], [Library], [TypeScript], [103], [2026-10-07], [MIT], [M], [*vendor* S], [Zero-dep PDFium WASM text/PNG; PDF attachments in media-intel],
[libopus-wasm], [Library], [TypeScript], [103], [2026-09-25], [MIT], [L], [*ignore* -], [Opus packets; telephony uses mulaw],
[fs-safe], [Library], [TypeScript], [62], [2026-10-08], [MIT], [H], [*vendor* S], [Root-bounded fs primitives for untrusted paths; npm dependency],
[ffmpeg-wasm], [Library], [TypeScript], [55], [2026-10-07], [MIT], [M], [*study* M], [LGPL WASM ffmpeg; slower than native, native ffmpeg already usable],
[rastermill], [Library], [TypeScript], [38], [2026-10-07], [MIT], [L], [*study* S], [Photon-based image ops; compare to current image path],
[proxyline], [Library], [TypeScript], [33], [2026-10-01], [MIT], [L], [*ignore* -], [Process-global proxy routing],
[libterminal], [Library], [TypeScript], [7], [2026-10-07], [MIT], [L], [*ignore* -], [Terminal protocol primitives],
[uirouter], [Library], [TypeScript], [4], [2026-10-07], [MIT], [L], [*ignore* -], [Empty description],
[wacli], [Messenger], [Go], [2,789], [2026-10-07], [MIT], [H], [*wrapper* M], [WhatsApp CLI via whatsmeow; --json, --read-only; basis for a whatsapp MCP],
[imsg], [Messenger], [Swift], [1,353], [2026-10-07], [MIT], [H], [*see R1a/R1b* -], [Swift iMessage CLI + JSON-RPC; analysed by siblings],
[discrawl], [Messenger], [Go], [852], [2026-10-07], [MIT], [M], [*study* S], [Discord archive; same crawlkit pattern; no EQStack Discord use],
[clickclack], [Messenger], [Go], [297], [2026-10-07], [MIT], [L], [*ignore* -], [Chat app for claws; not inspected],
[slacrawl], [Messenger], [Go], [237], [2026-10-07], [MIT], [M], [*study* S], [Slack archive; same pattern],
[wacrawl], [Messenger], [Go], [204], [2026-10-01], [MIT], [M], [*study* S], [WhatsApp archive crawler; second source if wacli insufficient],
[notcrawl], [Messenger], [Go], [134], [2026-10-07], [MIT], [L], [*ignore* -], [Notion crawler],
[gitcrawl], [Messenger], [Go], [124], [2026-10-07], [MIT], [L], [*ignore* -], [GitHub triage crawler],
[telecrawl], [Messenger], [Go], [86], [2026-10-07], [MIT], [M], [*skill* S], [Telegram Desktop tdata + Postbox reader; local only],
[crawlkit], [Messenger], [Go], [62], [2026-10-07], [MIT], [M], [*study* S], [Shared Go kit (store, backup, snapshot, tui); EQStack is TS so pattern only],
[clawdex], [Messenger], [Go], [56], [2026-10-01], [MIT], [H], [*study* S], [Contacts crawler to markdown repo; relevant to the contacts arc],
[crabline], [Messenger], [TypeScript], [32], [2026-10-07], [MIT], [M], [*study* S], [Deterministic mock servers for 12 channels incl. iMessage; QA pattern for telephony/imsg tests],
[graincrawl], [Messenger], [Go], [25], [2026-10-07], [MIT], [L], [*ignore* -], [Granola notes archive],
[crawlbar], [Messenger], [Swift], [25], [2026-10-07], [MIT], [L], [*ignore* -], [Menu bar for crawl apps],
[photoscrawl], [Messenger], [Go], [22], [2026-10-07], [MIT], [L], [*study* S], [Apple Photos crawler; media-intel adjacent; not inspected],
[imsgcrawl], [Messenger], [Go], [13], [2026-10-03], [MIT], [H], [*study* S], [Go archive of Messages.db; overlaps imsg-mcp archive; read snapshot logic],
[openclaw-windows-node], [Platform], [C\#], [2,138], [2026-10-08], [MIT], [L], [*ignore* -], [Windows companion (C\#)],
[esp-openclaw-node], [Platform], [C], [95], [2026-10-01], [Apache-2.0], [L], [*ignore* -], [ESP32 node],
[clawgo], [Platform], [Go], [85], [2026-10-07], [MIT], [L], [*ignore* -], [Go node],
[caclawphony], [Platform], [Elixir], [47], [2026-09-25], [Apache-2.0 (fork of openai/symphony)], [L], [*ignore* -], [Fork of openai/symphony (Elixir)],
[flawd-bot], [Platform], [JavaScript], [40], [2026-10-07], [CC0-1.0], [L], [*ignore* -], [Joke bot],
[casa], [Platform], [Swift], [37], [2026-05-30], [none], [L], [*ignore* -], [Archived HomeKit bridge],
[Swabble], [Platform], [Swift], [33], [2026-10-07], [MIT], [L], [*ignore* -], [Wake-word daemon],
[openclaw-windows-packaging], [Platform], [C\#], [3], [2026-10-08], [MIT], [L], [*ignore* -], [MSIX],
[openclaw-facetime], [Platform], [Objective-C], [1], [2026-10-07], [MIT], [L], [*ignore* -], [FaceTime capture],
[hermit], [Plugin SDK], [TypeScript], [36], [2026-10-07], [MIT], [L], [*ignore* -], [Empty description],
[cookbook], [Plugin SDK], [TypeScript], [34], [2026-09-25], [MIT], [L], [*study* S], [Example apps for OpenClaw SDK],
[plugin-inspector], [Plugin SDK], [JavaScript], [25], [2026-10-07], [MIT], [L], [*ignore* -], [Plugin compat checker],
[crabpot], [Plugin SDK], [JavaScript], [19], [2026-10-06], [MIT], [L], [*ignore* -], [Plugin testbed],
[kitchen-sink], [Plugin SDK], [JavaScript], [10], [2026-10-07], [MIT], [L], [*ignore* -], [Plugin fixture],
[tidepool], [Plugin SDK], [TypeScript], [7], [2026-10-07], [MIT], [L], [*ignore* -], [Toy plugins],
[reef], [Plugin SDK], [TypeScript], [6], [2026-10-07], [MIT], [L], [*ignore* -], [Empty description],
[krillswitch], [Plugin SDK], [TypeScript], [3], [2026-10-07], [MIT], [L], [*ignore* -], [Empty description],
[babelfish], [Plugin SDK], [TypeScript], [1], [2026-10-07], [MIT], [L], [*ignore* -], [Plugin adapter],
[openclaw-atif], [Plugin SDK], [TypeScript], [1], [2026-10-07], [MIT], [L], [*ignore* -], [Empty description],
[collab], [Plugin SDK], [TypeScript], [0], [2026-10-02], [MIT], [L], [*ignore* -], [Markdown co-editing],
[ocm], [Runtime], [Rust], [20], [2026-10-07], [MIT], [L], [*ignore* -], [Rust OpenClaw Manager; 20 stars],
[WebKit], [Runtime], [JavaScript], [4], [2026-10-07], [none (fork of oven-sh/WebKit)], [L], [*ignore* -], [Fork of oven-sh/WebKit (JSC); only for bun builds],
[bun], [Runtime], [Rust], [2], [2026-10-08], [NOASSERTION (fork of oven-sh/bun)], [H], [*see bun section* M], [Fork of oven-sh/bun (now Rust); nightly prereleases],
)